# Generated by Django 4.2.5 on 2023-11-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_userprofile'),
        ('profiles', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='shop.book'),
        ),
    ]
