# Generated by Django 4.2.5 on 2023-11-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_cartitem_book_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
